from enum import IntEnum

class AlarmId(IntEnum):
	ACAL = 112 # AccuCal II Error Code
	APPL = 20 # Application Shell Error
	APSH = 38 # Application Shell Error
	ARC = 53 # Arc Welding Application
	ASBN = 22 # Mnemonic Editor
	ATZN = 138 # AutoZone Error
	BBOX = 118 # Position Bumpbox Error
	BRCH = 144 # Brake Check Error
	CALM = 106 # CalMate Error
	CD = 82 # Coordinated Motion Softpart
	CMND = 42 # Command Processor Error
	CNTR = 73 # Continuous Turn Softpart
	COMP = 59 # Compensator Error
	COND = 4 # Condition Handler Error
	COPT = 37 # Common Options Error
	CPMO = 114 # Constant Path Error Code
	CUST = 97 # Customer-Specific Errors
	CVIS = 117 # Integrated Vision (Controller Vision)
	DIAG = 148 # IRDiagnostics
	DICT = 33 # Dictionary Processor
	DMDR = 84 # Dual Motion Drive Error
	DMER = 40 # Data Monitor Error
	DNET = 76 # DeviceNet Error
	DTBR = 149 # Data Transfer Between Robots
	DX = 72 # Delta Tool/Frame Softpart
	ELOG = 5 # Error Logger
	FILE = 2 # File System Error
	FLPY = 10 # Serial Floppy Disk System Error
	FORC = 91 # Impedance Control (Force Control)
	FRSY = 85 # Flash File System Error
	FXTL = 136 # C-Flex Tool Error
	HOST = 67 # Host Communications General Error
	HRTL = 66 # Host Communications Runtime Library Error
	IBS = 88 # InterBus-S Error
	ICRZ = 124 # IC Railzone Error
	IFPN = 153 # Interface Panel Error
	INTP = 12 # Interpreter Internal Error
	IRPK = 127 # IRPickTool Error
	ISD = 39 # Integral Servo Dispenser Error
	ISDT = 95 # Integral Servo Driven Tool Error
	JOG = 19 # Manual Jog Task Error
	KALM = 122 # KAREL Alarm Error
	LANG = 21 # Language Utility Error
	LECO = 109 # Arc Errors from Lincoln Electric
	LNTK = 44 # Line Tracking Error
	LSTP = 108 # Local Stop Error Codes
	MACR = 57 # Macro Option Error
	MARL = 83 # Material Removal Error
	MASI = 147 # Multi-Arm Sync Instructions Error
	MCTL = 6 # Motion Control Manager Error
	MEMO = 7 # Memory Manager Error
	MOTN = 15 # Motion Subsystem Error
	MUPS = 48 # Multi-Pass Motion Error
	OPTN = 65 # Option Installation Error
	OS = 0 # Operating System Error
	PALL = 115 # PalletTool Error
	PALT = 26 # Palletizing Application Error
	PICK = 132 # PickTool Error
	PMON = 28 # PC Monitor Error
	PNT1 = 86 # Paint Application Errors (Post V6.31)
	PNT2 = 137 # PaintTool Application Errors #2
	PRIO = 13 # Digital I/O Subsystem Error
	PROF = 92 # Profibus DP Error
	PROG = 3 # Program Interpreter Error
	PWD = 31 # Password Logging Error
	QMGR = 61 # KAREL Queue Manager Error
	RIPE = 130 # ROS IP Errors
	ROUT = 17 # SoftPart Built-in Routine for Interpreter Error
	RPC = 93 # RPC Error
	RPM = 43 # Root Pass Memorization Error
	RTCP = 89 # Remote TCP Error
	SCIO = 25 # Syntax Checking for Teach Pendant Programs Error
	SDTL = 123 # System Design Tool Error
	SEAL = 51 # Sealing Application Error
	SENS = 58 # Sensor Interface Error
	SHAP = 79 # Shape Generation Error
	SPOT = 23 # Spot Welding Application Error
	SPRM = 131 # Ramp Motion SoftPart Error
	SRIO = 1 # Serial Driver Error
	SRVO = 11 # Servo in Motion Sub-System Error
	SSPC = 69 # Special Space Checking Function Error
	SVGN = 30 # Servo Weld Gun Application Error
	SYST = 24 # System Error
	TAST = 47 # Through-Arc Seam Tracking Error
	TCPP = 46 # TCP Speed Prediction Error
	TG = 90 # Triggering Accuracy Error
	THSR = 60 # Touch Sensing SoftPart Error
	TJOG = 116 # Tracking Jog Error
	TMAT = 119 # Torch Mate Error
	TOOL = 29 # Servo Tool Change Error
	TPIF = 9 # Teach Pendant User Interface Error
	TRAK = 54 # Tracking SoftPart Error
	VARS = 16 # Variable Manager Subsystem Error
	WEAV = 45 # Weaving Error
	WNDW = 18 # Window I/O Manager Sub-System Error
	XMLF = 129 # XML Errors
