import clr
import os
clr.AddReference(os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "..",  'lib', 'UnderAutomation.Fanuc.dll')))
from UnderAutomation.Fanuc.Snpx.Internal import AlarmId as alarm_id

class AlarmId(int):
	ACAL = int(alarm_id.ACAL)
	APPL = int(alarm_id.APPL)
	APSH = int(alarm_id.APSH)
	ARC = int(alarm_id.ARC)
	ASBN = int(alarm_id.ASBN)
	ATZN = int(alarm_id.ATZN)
	BBOX = int(alarm_id.BBOX)
	BRCH = int(alarm_id.BRCH)
	CALM = int(alarm_id.CALM)
	CD = int(alarm_id.CD)
	CMND = int(alarm_id.CMND)
	CNTR = int(alarm_id.CNTR)
	COMP = int(alarm_id.COMP)
	COND = int(alarm_id.COND)
	COPT = int(alarm_id.COPT)
	CPMO = int(alarm_id.CPMO)
	CUST = int(alarm_id.CUST)
	CVIS = int(alarm_id.CVIS)
	DIAG = int(alarm_id.DIAG)
	DICT = int(alarm_id.DICT)
	DMDR = int(alarm_id.DMDR)
	DMER = int(alarm_id.DMER)
	DNET = int(alarm_id.DNET)
	DTBR = int(alarm_id.DTBR)
	DX = int(alarm_id.DX)
	ELOG = int(alarm_id.ELOG)
	FILE = int(alarm_id.FILE)
	FLPY = int(alarm_id.FLPY)
	FORC = int(alarm_id.FORC)
	FRSY = int(alarm_id.FRSY)
	FXTL = int(alarm_id.FXTL)
	HOST = int(alarm_id.HOST)
	HRTL = int(alarm_id.HRTL)
	IBS = int(alarm_id.IBS)
	ICRZ = int(alarm_id.ICRZ)
	IFPN = int(alarm_id.IFPN)
	INTP = int(alarm_id.INTP)
	IRPK = int(alarm_id.IRPK)
	ISD = int(alarm_id.ISD)
	ISDT = int(alarm_id.ISDT)
	JOG = int(alarm_id.JOG)
	KALM = int(alarm_id.KALM)
	LANG = int(alarm_id.LANG)
	LECO = int(alarm_id.LECO)
	LNTK = int(alarm_id.LNTK)
	LSTP = int(alarm_id.LSTP)
	MACR = int(alarm_id.MACR)
	MARL = int(alarm_id.MARL)
	MASI = int(alarm_id.MASI)
	MCTL = int(alarm_id.MCTL)
	MEMO = int(alarm_id.MEMO)
	MOTN = int(alarm_id.MOTN)
	MUPS = int(alarm_id.MUPS)
	OPTN = int(alarm_id.OPTN)
	OS = int(alarm_id.OS)
	PALL = int(alarm_id.PALL)
	PALT = int(alarm_id.PALT)
	PICK = int(alarm_id.PICK)
	PMON = int(alarm_id.PMON)
	PNT1 = int(alarm_id.PNT1)
	PNT2 = int(alarm_id.PNT2)
	PRIO = int(alarm_id.PRIO)
	PROF = int(alarm_id.PROF)
	PROG = int(alarm_id.PROG)
	PWD = int(alarm_id.PWD)
	QMGR = int(alarm_id.QMGR)
	RIPE = int(alarm_id.RIPE)
	ROUT = int(alarm_id.ROUT)
	RPC = int(alarm_id.RPC)
	RPM = int(alarm_id.RPM)
	RTCP = int(alarm_id.RTCP)
	SCIO = int(alarm_id.SCIO)
	SDTL = int(alarm_id.SDTL)
	SEAL = int(alarm_id.SEAL)
	SENS = int(alarm_id.SENS)
	SHAP = int(alarm_id.SHAP)
	SPOT = int(alarm_id.SPOT)
	SPRM = int(alarm_id.SPRM)
	SRIO = int(alarm_id.SRIO)
	SRVO = int(alarm_id.SRVO)
	SSPC = int(alarm_id.SSPC)
	SVGN = int(alarm_id.SVGN)
	SYST = int(alarm_id.SYST)
	TAST = int(alarm_id.TAST)
	TCPP = int(alarm_id.TCPP)
	TG = int(alarm_id.TG)
	THSR = int(alarm_id.THSR)
	TJOG = int(alarm_id.TJOG)
	TMAT = int(alarm_id.TMAT)
	TOOL = int(alarm_id.TOOL)
	TPIF = int(alarm_id.TPIF)
	TRAK = int(alarm_id.TRAK)
	VARS = int(alarm_id.VARS)
	WEAV = int(alarm_id.WEAV)
	WNDW = int(alarm_id.WNDW)
	XMLF = int(alarm_id.XMLF)

	def __repr__(self):
		for name, value in vars(AlarmId).items():
			if not name.startswith('_') and isinstance(value, int) and value == self:
				return name
		return str(int(self))
